server:
  port: 9999
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8888/eureka
spring:
  application:
    name: golden-gateway
  cloud.gateway:
    discovery:
      locator:
        enabled: true
        lowerCaseServiceId: true
    routes:
      - id: MICROSERVICE-API
        uri: lb://MICROSERVICE-API
        predicates:
          - Path=/demo/**

user:
  username: username
  password: password
  secretkey: getajob
